apiVersion: v1
kind: ServiceAccount
metadata:
  name: opsani-servo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opsani-servo
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opsani-servo-rw-resources
subjects:
- kind: ServiceAccount
  name: opsani-servo
roleRef:
  kind: Role
  name: opsani-servo
  apiGroup: rbac.authorization.k8s.io
